apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: api-hpa
  namespace: api
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: api-deployment  # Change this as per your deployment
  minReplicas: 1
  maxReplicas: 50
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 50
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 120  # Wait for 2 minutes before scaling down
      policies:
        - type: Percent
          value: 20  # Reduce by 20% of current pods at a time
          periodSeconds: 60  # Scale down every 60 seconds
    scaleUp:
      policies:
        - type: Percent
          value: 50  # Increase by 50% of current pods at a time
          periodSeconds: 15  # Scale up every 15 seconds